=== faburaya/imagetranscoder/ImageTranscoder/MetadataCopyMap.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="MetadataCopyMap"
    targetNamespace="http://3fd.codeplex.com/MetadataCopyMap.xsd"
    elementFormDefault="qualified"
    xmlns="http://3fd.codeplex.com/MetadataCopyMap.xsd"
    xmlns:tns="http://3fd.codeplex.com/MetadataCopyMap.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="listOfFormats">
        <xs:sequence>
            <xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="guid" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:token">
                                <xs:pattern value="\{[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\}"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="name" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:token">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="8"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="listOfMapCases">
        <xs:sequence>
            <xs:element name="case" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType mixed="true">
                    <xs:sequence>
                        <xs:element name="entry" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="metaFormat" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:token">
                                            <xs:minLength value="1"/>
                                            <xs:maxLength value="8"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="fromPath" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:token">
                                            <xs:minLength value="1"/>
                                            <xs:maxLength value="32"/>
                                            <xs:pattern value="(/[0-9a-zA-Z]+)*"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="toPath" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:token">
                                            <xs:minLength value="1"/>
                                            <xs:maxLength value="32"/>
                                            <xs:pattern value="(/[0-9a-zA-Z]+)*"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                                <xs:attribute name="onlyCommon" type="xs:boolean" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="srcFormat" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:token">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="8"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="destFormat" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:token">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="8"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="listOfItems">
        <xs:sequence>
            <xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:nonNegativeInteger">
                                <xs:maxExclusive value="65536"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="metaFormat" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:token">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="8"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="name" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:token">
                                <xs:minLength value="1"/>
                                <xs:maxLength value="32"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="rational" type="xs:boolean" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="metadata">
        <xs:complexType>
            <xs:all>
                <xs:element name="formats" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="container" type="listOfFormats" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="metadata"  type="listOfFormats" minOccurs="1" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="map" type="listOfMapCases" minOccurs="1" maxOccurs="1"/>
                <xs:element name="items" type="listOfItems" minOccurs="1" maxOccurs="1"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== faburaya/imagetranscoder/ImageTranscoder/MetadataCopyMap.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Configures how application handles metadata -->
<metadata xmlns="http://3fd.codeplex.com/MetadataCopyMap.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:tns="http://3fd.codeplex.com/MetadataCopyMap.xsd"
          xsi:schemaLocation="http://3fd.codeplex.com/MetadataCopyMap.xsd MetadataCopyMap.xsd">
    
    <!-- Tells the application how the GUID's used by WIC API relate to the format names used in this XML -->
    <formats>
        <container>
            <entry guid="{163bcc30-e2e9-4f0b-961d-a3e9fdb788a3}" name="tiff"/>
            <entry guid="{57a37caa-367a-4540-916b-f183c5093a4b}" name="jpegxr"/>
            <entry guid="{19e4a5aa-5662-4fc5-a0c0-1758028e1057}" name="jpeg"/>
        </container>
        <metadata>
            <entry guid="{79007028-268D-45D6-A3C2-354E6A504BC9}" name="App0"/>
            <entry guid="{8FD3DFC3-F951-492B-817F-69C2E6D9A5B0}" name="App1"/>
            <entry guid="{326556A2-F502-4354-9CC0-8E3F48EAF6B5}" name="App13"/>
            <entry guid="{537396C6-2D8A-4BB6-9BF8-2F0A8E2A3ADF}" name="IFD"/>
            <entry guid="{1C3C4F9D-B84A-467D-9493-36CFBD59EA57}" name="EXIF"/>
            <entry guid="{7134AB8A-9351-44AD-AF62-448DB6B502EC}" name="GPS"/>
            <entry guid="{BB5ACC38-F216-4CEC-A6C5-5F6E739763A9}" name="XMP"/>
            <entry guid="{16100D66-8570-4BB9-B92D-FDA4B23ECE67}" name="IRB"/>
            <entry guid="{4FAB0914-E129-4087-A1D1-BC812D45A7B5}" name="IPTC"/>
            <entry guid="{0010568C-0852-4E6A-B191-5C33AC5B0430}" name="8BIMIPTC"/>
        </metadata>
    </formats>

    <!-- How to copy metadata in several cases of one container type to another.
         The application will only be able to copy metadata from cases listed below,
         or when container format for both source and destination are the same. -->
    <map>
        <case srcFormat="tiff" destFormat="jpeg">
            <entry metaFormat="IFD"  fromPath="/ifd"                   toPath="/app1/ifd"                onlyCommon="true"/>
            <entry metaFormat="XMP"  fromPath="/ifd/xmp"               toPath="/xmp"                     onlyCommon="false"/>
            <entry metaFormat="EXIF" fromPath="/ifd/exif"              toPath="/app1/ifd/exif"           onlyCommon="true"/>
            <entry metaFormat="GPS"  fromPath="/ifd/gps"               toPath="/app1/ifd/exif"           onlyCommon="true"/>
            <entry metaFormat="IPTC" fromPath="/ifd/irb/8bimiptc/iptc" toPath="/app13/irb/8bimiptc/iptc" onlyCommon="false"/>
        </case>
        <case srcFormat="jpeg" destFormat="tiff">
            <entry metaFormat="IFD"  fromPath="/app1/ifd"                toPath="/ifd"                   onlyCommon="true"/>
            <entry metaFormat="XMP"  fromPath="/xmp"                     toPath="/ifd/xmp"               onlyCommon="false"/>
            <entry metaFormat="EXIF" fromPath="/app1/ifd/exif"           toPath="/ifd/exif"              onlyCommon="true"/>
            <entry metaFormat="IPTC" fromPath="/app13/irb/8bimiptc/iptc" toPath="/ifd/irb/8bimiptc/iptc" onlyCommon="false"/>
        </case>
        <case srcFormat="jpegxr" destFormat="jpeg">
            <entry metaFormat="IFD"  fromPath="/ifd"                   toPath="/app1/ifd"                onlyCommon="true"/>
            <entry metaFormat="XMP"  fromPath="/ifd/xmp"               toPath="/xmp"                     onlyCommon="false"/>
            <entry metaFormat="EXIF" fromPath="/ifd/exif"              toPath="/app1/ifd/exif"           onlyCommon="true"/>
            <entry metaFormat="GPS"  fromPath="/ifd/gps"               toPath="/app1/ifd/exif"           onlyCommon="true"/>
            <entry metaFormat="IPTC" fromPath="/ifd/irb/8bimiptc/iptc" toPath="/app13/irb/8bimiptc/iptc" onlyCommon="false"/>
        </case>
        <case srcFormat="jpeg" destFormat="jpegxr">
            <entry metaFormat="IFD"  fromPath="/app1/ifd"                toPath="/ifd"                   onlyCommon="true"/>
            <entry metaFormat="XMP"  fromPath="/xmp"                     toPath="/ifd/xmp"               onlyCommon="false"/>
            <entry metaFormat="EXIF" fromPath="/app1/ifd/exif"           toPath="/ifd/exif"              onlyCommon="true"/>
            <entry metaFormat="IPTC" fromPath="/app13/irb/8bimiptc/iptc" toPath="/ifd/irb/8bimiptc/iptc" onlyCommon="false"/>
        </case>
        <case srcFormat="tiff" destFormat="jpegxr">
            <entry metaFormat="IFD"  fromPath="/ifd"                   toPath="/ifd"                   onlyCommon="true"/>
            <entry metaFormat="XMP"  fromPath="/ifd/xmp"               toPath="/ifd/xmp"               onlyCommon="false"/>
            <entry metaFormat="EXIF" fromPath="/ifd/exif"              toPath="/ifd/exif"              onlyCommon="true"/>
            <entry metaFormat="GPS"  fromPath="/ifd/gps"              toPath="/ifd/gps"                onlyCommon="true"/>
            <entry metaFormat="IPTC" fromPath="/ifd/irb/8bimiptc/iptc" toPath="/ifd/irb/8bimiptc/iptc" onlyCommon="false"/>
        </case>
        <case srcFormat="jpegxr" destFormat="tiff">
            <entry metaFormat="IFD"  fromPath="/ifd"                   toPath="/ifd"                   onlyCommon="true"/>
            <entry metaFormat="XMP"  fromPath="/ifd/xmp"               toPath="/ifd/xmp"               onlyCommon="false"/>
            <entry metaFormat="EXIF" fromPath="/ifd/exif"              toPath="/ifd/exif"              onlyCommon="true"/>
            <entry metaFormat="GPS"  fromPath="/ifd/gps"              toPath="/ifd/gps"                onlyCommon="true"/>
            <entry metaFormat="IPTC" fromPath="/ifd/irb/8bimiptc/iptc" toPath="/ifd/irb/8bimiptc/iptc" onlyCommon="false"/>
        </case>
    </map>

    <!-- The items that are common to several container formats -->
    <items>
        <entry id="0"     metaFormat="GPS"  rational="false" name="GPSVersionID"/>
        <entry id="1"     metaFormat="GPS"  rational="false" name="GPSLatitudeRef"/>
        <entry id="2"     metaFormat="GPS"  rational="true"  name="GPSLatitude"/>
        <entry id="3"     metaFormat="GPS"  rational="false" name="GPSLongitudeRef"/>
        <entry id="4"     metaFormat="GPS"  rational="true"  name="GPSLongitude"/>
        <entry id="5"     metaFormat="GPS"  rational="false" name="GPSAltitudeRef"/>
        <entry id="6"     metaFormat="GPS"  rational="true"  name="GPSAltitude"/>
        <entry id="7"     metaFormat="GPS"  rational="true"  name="GPSTimeStamp"/>
        <entry id="8"     metaFormat="GPS"  rational="false" name="GPSSatellites"/>
        <entry id="9"     metaFormat="GPS"  rational="false" name="GPSStatus"/>
        <entry id="10"    metaFormat="GPS"  rational="false" name="GPSMeasureMode"/>
        <entry id="11"    metaFormat="GPS"  rational="true"  name="GPSDOP"/>
        <entry id="12"    metaFormat="GPS"  rational="false" name="GPSSpeedRef"/>
        <entry id="13"    metaFormat="GPS"  rational="true"  name="GPSSpeed"/>
        <entry id="14"    metaFormat="GPS"  rational="false" name="GPSTrackRef"/>
        <entry id="15"    metaFormat="GPS"  rational="true"  name="GPSTrack"/>
        <entry id="256"   metaFormat="IFD"  rational="false" name="ImageWidth"/>
        <entry id="257"   metaFormat="IFD"  rational="false" name="ImageLength"/>
        <entry id="258"   metaFormat="IFD"  rational="false" name="BitsPerSample"/>
        <entry id="259"   metaFormat="IFD"  rational="false" name="Compression"/>
        <entry id="262"   metaFormat="IFD"  rational="false" name="PhotometricInterpretation"/>
        <entry id="274"   metaFormat="IFD"  rational="false" name="Orientation"/>
        <entry id="277"   metaFormat="IFD"  rational="false" name="SamplesPerPixel"/>
        <entry id="284"   metaFormat="IFD"  rational="false" name="PlanarConfiguration"/>
        <entry id="530"   metaFormat="IFD"  rational="false" name="YCbCrSubSampling"/>
        <entry id="531"   metaFormat="IFD"  rational="false" name="YCbCrPositioning"/>
        <entry id="282"   metaFormat="IFD"  rational="false" name="XResolution"/>
        <entry id="283"   metaFormat="IFD"  rational="false" name="YResolution"/>
        <entry id="296"   metaFormat="IFD"  rational="false" name="ResolutionUnit"/>
        <entry id="306"   metaFormat="IFD"  rational="false" name="DateTime"/>
        <entry id="270"   metaFormat="IFD"  rational="false" name="ImageDescription"/>
        <entry id="271"   metaFormat="IFD"  rational="false" name="Make"/>
        <entry id="272"   metaFormat="IFD"  rational="false" name="Model"/>
        <entry id="305"   metaFormat="IFD"  rational="false" name="Software"/>
        <entry id="315"   metaFormat="IFD"  rational="false" name="Artist"/>
        <entry id="33432" metaFormat="IFD"  rational="false" name="Copyright"/>
        <entry id="338"   metaFormat="IFD"  rational="false" name="ExtraSamples"/>
        <entry id="254"   metaFormat="IFD"  rational="false" name="NewSubfileType"/>
        <entry id="278"   metaFormat="IFD"  rational="false" name="RowsPerStrip"/>
        <entry id="279"   metaFormat="IFD"  rational="false" name="StripByteCounts"/>
        <entry id="273"   metaFormat="IFD"  rational="false" name="StripOffsets"/>
        <entry id="36864" metaFormat="EXIF" rational="false" name="ExifVersion"/>
        <entry id="40960" metaFormat="EXIF" rational="false" name="FlashpixVersion"/>
        <entry id="40961" metaFormat="EXIF" rational="false" name="ColorSpace"/>
        <entry id="40962" metaFormat="EXIF" rational="false" name="PixelXDimension"/>
        <entry id="40963" metaFormat="EXIF" rational="false" name="PixelYDimension"/>
        <entry id="37500" metaFormat="EXIF" rational="false" name="MakerNote"/>
        <entry id="37510" metaFormat="EXIF" rational="false" name="UserComment"/>
        <entry id="36867" metaFormat="EXIF" rational="false" name="DateTimeOriginal"/>
